[settings]
timeout = 120
name = "asset-hub-rococo"

[relaychain]
default_path = "polkadot"
default_command = "polkadot"
default_args = ["-lparachain=debug"]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
balance = 1000000000000

[[relaychain.nodes]]
name = "bob"
validator = true
balance = 1000000000000

[[parachains]]
id = 1000
balance = 1000000000000
chain_spec_path = "asset-hub-plain.json"


  [[parachains.collator]]
  name      = "collator01"
  path      = "polkadot-parachain"
  command   = "polkadot-parachain"
  args      = [
    "--collator",
    "--pruning", "archive",
    "-lparachain=debug",
    "--ws-external",
    "--rpc-external",
  ]
  ws_port   = 42070    # WebSocket RPC
  rpc_port  = 42069    # HTTP RPC
  base_port = 30333    # P2P port range starts here (30333/30334/…)
