[package]
name = "subxt-app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
subxt = { version = "0.42.1", features = ["unstable-light-client"] }
subxt-signer = "0.42.1"
tokio = { version = "1.45.1", features = ["full"]}
