[package]
name = "subxt-app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rand = "0.9.1"
subxt = "0.42.1"
subxt-signer = "0.42.1"
tokio = { version = "1.45.1", features = ["full"]}
